env:
  global:
    - CC_TEST_REPORTER_ID=023abfbf4ae749013ab7141e0eac40b50cf7714410a9c8ffdf73145a9a571a14

sudo: required

language: python
python: 
  - "3.6.1"
install: "pip install -r requirements.txt"

services:
  - docker

before_install:
-  docker-compose build

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - docker-compose up -d
  - docker-compose run web ./event_microservice/manage.py makemigrations
  - docker-compose run web ./event_microservice/manage.py migrate
  - docker-compose run web bash -c "cd event_microservice/ && coverage run --source=. manage.py test"
  - docker-compose run web bash -c "cd event_microservice/ && coverage report"

after_success:
  - docker-compose run -e TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST -e TRAVIS="$TRAVIS" -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" web bash -c "cd event_microservice/ && coveralls"
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
